import "@/styles/globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Providers from "./providers";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Feedback App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
